### ISSUE TITLE
Google Chrome U2F API decommission

### ISSUE THREAD

**Issue by klslowik** [nextcloud/twofactor_u2f#988] opened 2022-02-16 17:35 UTC
Two-Factor U2F doesn't work with new version Chrome

https://www.yubico.com/blog/google-chrome-u2f-api-decommission-what-the-change-means-for-your-users-and-how-to-prepare/

**Comment by ChristophWurst** [comment] 2022-02-17 07:44
Duplicate of https://github.com/nextcloud/twofactor_u2f/issues/947

**Closed by ChristophWurst** 2022-02-17 07:44 UTC
