### ISSUE TITLE
U2F broken after upgrade to Nextcloud 15

### ISSUE THREAD

**Issue by Anonymous43523** [nextcloud/twofactor_u2f#325] opened 2019-01-06 05:54 UTC
### Steps to reproduce
1.  Upgrade Nextcloud from 14 to 15 with previously working U2F authentication.
2.  Attempt to log in.
3.  Receive error message "Sign failed."

### Expected behaviour
Tell us what should happen
U2F should work.

### Actual behaviour
Tell us what happens instead
Error message "Sign failed" and unable to log in.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:**  Apache

**Database:** MariaDB

**PHP version:** 7.2

**Version:** (see admin page) App version 2.1.0, Nextcloud version 15

**Updated from an older version or fresh install:** Updated and fresh install (removed app and reinstalled as troubleshooting after Nextcloud upgrade)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

Enabled:
  - accessibility: 1.1.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - passwords: 2019.1.0
  - phonetrack: 0.4.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - twofactor_u2f: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - sharebymail
  - survey_client
  - theming
  - user_external
  - user_ldap

**The content of config/config.php:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "[REDACTED]"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "[REDACTED]",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

#### Client configuration
**Browser:**
Pale Moon 28.2.1, using Firefox U2F Support Add-on 1.0.1

**Operating system:**
Linux Mint 17.1

##### Web server error log
```
Insert your webserver log here
```
(Nothing related to this issue in error log)

##### Server log (data/nextcloud.log)
```
Insert your server log here
```
(Nothing related to this issue in access log)

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

could not sign u2f challenge Error: Sign failed
Stack trace:
u@https://[REDACTED]/apps/twofactor_u2f/js/challenge.js?v=160f7233:33:14231
e.sign/</</<@https://[REDACTED]/apps/twofactor_u2f/js/challenge.js?v=160f7233:33:15283
  
challenge.js:60:17630
Error: Sign failed

Log from U2F add-on:

EB1 sign https://[REDACTED] [{challenge:"[REDACTED]", appId:"[REDACTED]"}] null
EB2 /home/[REDACTED]/extensions/u2f4moz@prefiks.org/bin/linux_x86_64-gcc3/u2f
EB3 ({killed:false, exitCode:(void 0), signalCode:(void 0), stdin:{readable:false, writable:false, encoding:null}, stdout:{readable:false, writable:false, encoding:null}, stderr:{readable:false, writable:false, encoding:null}})
stdin s001b00010061 https://[REDACTED]{"challenge":"[REDACTED]","appId":"https://[REDACTED]"}
EBD e0046{"errorCode": 2, "errorMessage":"authenticate:error in JSON handling"}
exit 1 null

-----EDIT-----

I stepped through the Javascript involved with the authentication and found that neither the key_handle value nor the version value are being properly passed from the Nextcloud U2F app functions to the authenticator addon functions.  The values of both of those remain undefined in the U2F addon functions and hence the authentication fails as no key_handle value is presented to the U2F device.

I was able to successfully log in using the following process:

1.  Open the Javascript debugger in Pale Moon.
2.  Load the Nextcloud login page.
3.  Set a breakpoint on line 68 of content-worker.js from the Add-on SDK. The file path is  resource://gre/modules/commonjs/sdk/content/content-worker.js (This exact line was found by single-stepping from another breakpoint set in the content-script.js from the U2F addon.)
4.  Enter valid user credentials.
5.  Single-step (F11) through the code until the variable k = "keyHandle".
6.  Change the value of the variable v from undefined to the string value of key_handle found in the oc_twofactor_u2f_registrations table in the Nextcloud database.
7.  Click the resume button (F8) to continue to run the rest of the code normally.  This triggers the prompt to push the button on the U2F device and allows the login to continue as expected.  I had to click the run option in the debugger a couple more times as the breakpoint was hit again during the login process.

I found that steps 5 through 7 must be completed in under 30 seconds to avoid triggering a timeout and causing the login process to fail.

**Comment by ChristophWurst** [comment] 2019-01-07 13:18
Thanks for the detailed report. I will look into this.

**Comment by Anonymous43523** [comment] 2019-01-07 16:13
After further testing it looks like this is related to a bug in u2f-api.  I was able to fix the issue on my server by modifying the u2f-api code.  This doesn't look like a bug in twofactor_u2f so this ticket can probably be closed at this point.

Here's how to fix it, for anyone that lands here from Google, Bing, DDG, or wherever:

After downloading and compiling this app from source (in order to pull down all dependencies, there's probably a faster way to do this but I don't work with the frameworks used by nextcloud_u2f), modify the file **twofactor_u2f/node_modules/u2f-api/dist/lib/u2f-api.js** as follows:

Near the end of the file, find the following line: (at the time of writing this, it was 6th from the end, line 138)
`u2f.sign(appId, challenge, signRequests, callback, timeout);`

Change it to the following:
`u2f.sign(appId, challenge, regKeys, callback, timeout);`

Add the following line of code directly above the `u2f.sign(` line: (insert a line, don't overwrite anything)
`let regKeys = signRequests.map(x => { return {keyHandle:x.keyHandle, version:x.version}; });`

The code block should now look like this:
`var appId = signRequests[0].appId;`
`var challenge = signRequests[0].challenge;`
`let regKeys = signRequests.map(x => { return {keyHandle:x.keyHandle, version:x.version}; });`
`u2f.sign(appId, challenge, regKeys, callback, timeout);`

Save the file and rebuild the app.  Copy it to your server using whatever method you prefer (instructions for that found elsewhere.)

I tested this in Pale Moon 28.2.1 with the Firefox U2F support add-on 1.0.1, Firefox 64, and Google Chrome 71 to verify that it works.  I verified that it accepts the registered U2F key and rejects an unregistered key as it should.  I also verified that it works properly with multiple keys registered.  I only have two U2F keys at the moment so I was unable to test for proper rejection of an unregistered key when multiple keys are registered.  Someone with three or more U2F keys will need to test that.  I have this change in place on my production Nextcloud server.

**Comment by ChristophWurst** [comment] 2019-01-07 16:15
If it's indeed an issue with the upstream lib it might be worth to report at https://github.com/grantila/u2f-api/issues.

**Comment by dimm0** [comment] 2019-01-12 03:32
See the same after updating 15.0.0 to 15.0.2

**Comment by ChristophWurst** [comment] 2019-01-14 07:56
See https://github.com/nextcloud/twofactor_u2f/pull/335 for the updated u2f lib. Does that fix the issue for you?

I will try to reproduce this and release an update if necessary.

**Comment by ChristophWurst** [comment] 2019-01-14 11:49
With the old version of the lib I get 
![bildschirmfoto von 2019-01-14 12-43-14](https://user-images.githubusercontent.com/1374172/51110840-3f228300-17fa-11e9-9fd1-23e9c04a5184.png) when I let u2f time out on login. If I press the "Retry" button I click my device button and get logged in as expected.

On master (update u2f lib) it works just the same:

![bildschirmfoto von 2019-01-14 12-48-49](https://user-images.githubusercontent.com/1374172/51111015-c7a12380-17fa-11e9-89dd-c159aaa3aa1c.png)

**Comment by sbidy** [comment] 2019-01-14 12:46
Hey, with my 15.0.1 NC and the 2.1.0 (store) U2F app I get the same error messages but I can't log in. I'll also get an error message `Registration failed` at the `settings.js` if I try to re-register a new U2F stick (Yubico 4).

**Comment by dimm0** [comment] 2019-01-14 16:55
Update from 15.0.0.10 to 15.0.2 broke this for me

**Comment by ChristophWurst** [comment] 2019-01-14 16:56
Screenshots and/or logs would help *a lot*.

**Comment by dimm0** [comment] 2019-01-15 00:00
<img width="1430" alt="screen shot 2019-01-14 at 3 59 31 pm" src="https://user-images.githubusercontent.com/1425007/51149087-705c7c80-1815-11e9-8f74-4082602cb8ff.png">

Not sure where to get logs from

**Comment by ChristophWurst** [comment] 2019-01-18 09:03
I gave this another shot. This time on two production instances of Nextcloud 15: one with 15.0.0 and another one with 15.0.2. This is what I get:

I see the error when I let it time out:
![bildschirmfoto von 2019-01-18 10-00-19](https://user-images.githubusercontent.com/1374172/51376216-135c1180-1b08-11e9-887c-9a82bdd4ebc1.png)
But it offers me to retry:
![bildschirmfoto von 2019-01-18 10-00-03](https://user-images.githubusercontent.com/1374172/51376217-135c1180-1b08-11e9-85cd-601213a3735d.png)
If I click that, I'm getting logged in.

---

![bildschirmfoto von 2019-01-18 09-58-26](https://user-images.githubusercontent.com/1374172/51376271-34246700-1b08-11e9-80df-5ee773cc91ad.png)
Same timeout error on 15.0.0. It also lets me retry.

---

Can you confirm that the login page works?

**Comment by ChristophWurst** [comment] 2019-01-18 09:07
Please be a bit more precise with your reports. The original report talks about login. Some of the others about the registration (settings page).

I can confirm that there is a lack of error handling on the registration page. I could trigger it by attempting to register an already registered key. The loading spinner remains, an error message appears in the console.

**Comment by ChristophWurst** [comment] 2019-01-18 09:10
> I can confirm that there is a lack of error handling on the registration page

-> now tracked at https://github.com/nextcloud/twofactor_u2f/issues/343.

**Comment by ChristophWurst** [comment] 2019-01-18 13:07
I had a longer debugging session with @rullzer today. Luckily he has a setup where the same symptoms show up. We gathered the following symptoms:

* The u2f error is 4 DEVICE_INELIGIBLE -> https://developers.yubico.com/U2F/Libraries/Client_error_codes.html
* On the same instance, the u2f key can be registered and used for a second user
* The registrations data passed to the u2f lib has the same properties on the working and broken setup

This currently leads to the conclusion that there is an issue with the key handle. I don't know if it somehow changed on the server or the key or is passed differently now, but that's why u2f refuses the sign request.

**Comment by ChristophWurst** [comment] 2019-01-20 13:49
Interestingly enough, my old u2f registrations on https://sentry.io also stopped working until I re-register the keys. AFAIK they use the exact same u2f lib as we do.

**Comment by prezeskk** [comment] 2019-01-25 13:50
On two Nextcloud 15.0.2 servers (ubuntu 18.04.1/php 7.2.10 & debian 9.7/php 7.2.13) u2f not working.
On third server (slackware 14.2/php 7.2.14) Nextcloud 15.0.2 u2f working as expected (on login & settings page). All server configs are the same

**Comment by prezeskk** [comment] 2019-01-28 16:54
On all servers u2f keys working before upgrade to version 15.0.2 (keys added in version 13.x).
After update to version 15.0.2 on debian & ubuntu keys stop working (on login & settings page).
Only on slackware u2f still working.
How to enable debug log?

**Comment by ChristophWurst** [comment] 2019-01-29 07:59
> Not sure how it could help

As explained in my previous comments this is the only difference I've found between the systems that work and those that don't. If you know what the real issue is or have any ideas please let me know. I'm happy for all input that helps us resolve this.

**Comment by ChristophWurst** [comment] 2019-01-29 08:00
> Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

Where's that error coming from? Can you trace that?

**Comment by ChristophWurst** [comment] 2019-01-29 08:02
You can try the latest development version which logs a bit more on failure: [twofactor_u2f.tar.gz](https://github.com/nextcloud/twofactor_u2f/files/2806575/twofactor_u2f.tar.gz)

**Comment by prezeskk** [comment] 2019-01-29 08:52
Log from development version

```
could not sign u2f challenge 
​code: 2
​type: "BAD_REQUEST"
​
Error: "Sign failed"
	u https://ubuntu.lan/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:14900
	sign https://ubuntu.lan/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:16098
	sign https://ubuntu.lan/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:16059
	sign https://ubuntu.lan/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:15915
```

**Comment by ChristophWurst** [comment] 2019-01-29 08:59
Bingo! So this is unexpected. Because on @rullzer's affected instance we saw error code 4.

Code 2 means
![bildschirmfoto von 2019-01-29 09-57-48](https://user-images.githubusercontent.com/1374172/51896267-5b9eed80-23ac-11e9-8a60-2011529c66ab.png)

(from https://developers.yubico.com/U2F/Libraries/Client_error_codes.html)

Did you change your domain? Did you change any config in Nextcloud? It might be possible that Nextcloud now generates a different server host. We use this code to generate the APP_ID:

```php
$url = $this->request->getServerProtocol() . '://' . $this->request->getServerHost();
new U2F($url);
```

**Comment by ChristophWurst** [comment] 2019-01-29 09:34
Is anybody using a proxy in front of Nextcloud?

**Comment by prezeskk** [comment] 2019-01-29 09:41
On this two not working servers I have reverse proxy

**Comment by ChristophWurst** [comment] 2019-01-29 09:45
And the working instance is served directly?

**Comment by prezeskk** [comment] 2019-01-29 09:45
Yes

**Comment by prezeskk** [comment] 2019-01-29 09:57
Is there any chance of using proxy in configuration?
Servers have internal addressing

**Comment by ChristophWurst** [comment] 2019-01-29 10:14
See https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html for correct configuration. It's very likely that if the config changes (or if it was not configured before but is now) that u2f won't work anymore as the app id is encoded in the registrations and certificates of u2f.

**Comment by prezeskk** [comment] 2019-01-29 10:23
After add proxy config error is like this
```
could not sign u2f challenge 
Object { type: "DEVICE_INELIGIBLE", code: 4 }

Error: "Sign failed"
	u https://oc.cmza.pl/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:14900
	sign https://oc.cmza.pl/apps/twofactor_u2f/js/challenge.js?v=66508372-19:33:16098
```

**Comment by ir0nhide** [comment] 2019-01-29 20:40
I'm also using nextcloud behind a proxy and got a code 2 error (BAD_REQUEST) with the development version of twofactor_u2f plugin. Solved this issue by adding this line to my config.php:
`'overwriteprotocol' => 'https',` 
Now everything is working again. Thanks!

**Comment by andrewmeyer** [comment] 2019-01-30 18:06
> I'm also using nextcloud behind a proxy and got a code 2 error (BAD_REQUEST) with the development version of twofactor_u2f plugin. Solved this issue by adding this line to my config.php:
> `'overwriteprotocol' => 'https',`
> Now everything is working again. Thanks!

At an initial glance, this fixed my setup (ssl termination on haproxy), but I will need to do more testing to confirm

**Comment by FoseFx** [comment] 2019-01-30 19:06
> I'm also using nextcloud behind a proxy and got a code 2 error (BAD_REQUEST) with the development version of twofactor_u2f plugin. Solved this issue by adding this line to my config.php:
> `'overwriteprotocol' => 'https',`
> Now everything is working again. Thanks!

Can confirm.

**Comment by ChristophWurst** [comment] 2019-01-31 07:56
Great to hear that we could resolve this for so many of you. I checked with @rullzer again and it turned out he has changed domains recently. Since the domain is used as *app id* in u2f and part of the registration, this will make the u2f registration unusable.

I'm closing this ticket now.

**Closed by ChristophWurst** 2019-01-31 07:56 UTC
Labels: 0. to triage, bug

**Comment by F13** [comment] 2019-02-27 16:05
If I'm understanding this thread correctly, I must always use the same domain to access my nextcloud instance, or else U2F will fail? Or, else, I could set the `overridehost` parameter for the proxy, but then I imagine that bypasses trusted domain protection. Is all that correct?

**Comment by ChristophWurst** [comment] 2019-02-28 08:42
Yep, that is a limitation of U2F. You can't use the same key registration from different domains.

> Or, else, I could set the `overridehost` parameter for the proxy, but then I imagine that bypasses trusted domain protection. Is all that correct?

What do you mean? The overridden host should be in your trusted domain list. Ideally, there is just one entry in that list.

**Comment by F13** [comment] 2019-02-28 15:38
Thanks for the info. I didn't realize that limitation of U2F.

What I meant was that if I set `overridehost` to `domain.tld`, it no longer matters what domain is used to access the instance, as every access which goes through the proxy will be interpreted as coming from `domain.tld`. As such there is no longer any trusted domain protection. That's what I was understanding, at least.

**Comment by ChristophWurst** [comment] 2019-03-01 07:47
Yep, makes sense.

**Comment by F13** [comment] 2019-03-01 21:00
Okay, thanks for confirming.
