### ISSUE TITLE
Codesigning Error

### ISSUE THREAD

**Issue by My1** [nextcloud/twofactor_u2f#20] opened 2016-12-17 15:36 UTC
I just literally downloaded the addon-archive file from the addon website and it gives me a code signing error:

```
Results
=======
- twofactor_u2f
	- INVALID_HASH
		- vendor/yubico/u2flib-server/README.adoc

Raw output
==========
Array
(
    [twofactor_u2f] => Array
        (
            [INVALID_HASH] => Array
                (
                    [vendor/yubico/u2flib-server/README.adoc] => Array
                        (
                            [expected] => 2d2e6a59a43eb63310ad6f491abe7b93cec7c8b5c866728b404f89c0ec47fe67b0009fae7fa38dd8ff8c88d5605556bf7b107d7ea704d122d01e5142d006322a
                            [current] => a91d9337cadaf5018990069e81872d282fb96e829d2e042417bcd3bf713f10eda4c487a6d21748e2e39447ec351656cfa00d01280dbe4d17f895b6870cb137f1
                        )
                )
        )
)
```
that file just reads `README` both in the addon and in the u2flib server files from yubico themselves

**Comment by ChristophWurst** [comment] 2016-12-17 15:43
> I just literally downloaded the file from the addon website and it gives me a code signing error:

Why did you replace that file?

**Comment by My1** [comment] 2016-12-17 15:46
I didnt replace the file. I just re-uploaded the whole addon

**Comment by My1** [comment] 2016-12-17 15:48
The file which i loaded from the addon page was the archive of the addon

**Comment by My1** [comment] 2016-12-17 15:49
And i just extracted that and re-uploaded it to the Webserver (sorry for multi-comment, mobile github doesn't have comment editing function)

**Comment by ChristophWurst** [comment] 2016-12-18 18:36
Could you please tell me how to reproduce this? I'm not sure whether I understand your problem.

**Comment by My1** [comment] 2016-12-18 18:47
Download the package from the nc plugin website, extract it, upload it to the server and see the code signing issue.

**Comment by ChristophWurst** [comment] 2016-12-18 18:59
I cannot reproduce. What I've tried:
```bash
wget https://download.nextcloud.com/server/releases/nextcloud-11.0.0.zip
unzip nextcloud-11.0.0.zip 
cd nextcloud/
php -f occ maintenance:install --database sqlite --admin-pass 'testtest'
cd apps/
wget https://github.com/nextcloud/twofactor_u2f/releases/download/0.1/twofactor_u2f.tar.gz
tar xf twofactor_u2f.tar.gz 
cd ..
php occ app:enable twofactor_u2f
php occ integrity:check-app twofactor_u2f
```

http://localhost:8080/index.php/settings/integrity/failed says "No errors have been found."

Did that really happen on a clean install? Why did you extract and upload the app's files manually?

**Comment by My1** [comment] 2016-12-18 19:08
okay weird.

well I dont have shell access so I cant really extract on the host.

also upon manual check the results are the same that I get at first.

![screenshot 90](https://cloud.githubusercontent.com/assets/6696524/21295823/a33cf6be-c55d-11e6-969a-37b1efaefb11.png)
![screenshot 91](https://cloud.githubusercontent.com/assets/6696524/21295824/a33db19e-c55d-11e6-84ab-876cc8f0ee9a.png)

**Comment by ChristophWurst** [comment] 2016-12-18 19:25
So why didn't you use Nextcloud's app settings page to install the app? Usually there is no need to upload/extract anything manually. Otherwise I'd say we close this issue as it's not reproducible here. Maybe uninstalling and re-installing the app helps?

**Comment by My1** [comment] 2016-12-18 19:27
wait what, this is possible? never knew that. I dont see any option on the addon page to install this thing

**Comment by ChristophWurst** [comment] 2016-12-18 19:36
> wait what, this is possible? never knew that. I dont see any option on the addon page to install this thing
> the only method I know is extracting this thing into the apps folder and then enable it, that's what I used ever since OC6

You really should take a look at the documentation: https://docs.nextcloud.com/server/11/admin_manual/installation/apps_management_installation.html

**Comment by My1** [comment] 2016-12-18 19:38
okay until including OC8 you needed to manually DL and upload them, and that's the way I did that ever since.

**Comment by ChristophWurst** [comment] 2017-04-03 08:30
I'm closing this ticket now because there hasn't been any activity for more than tree months and I still cannot reproduce this problem.

**Closed by ChristophWurst** 2017-04-03 08:30 UTC
Labels: needs info
